[env:esp32dev]
platform = espressif32@^6.6.0
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600
upload_port   = /dev/ttyUSB0
monitor_port  = /dev/ttyUSB0

monitor_filters =
  time
  colorize

board_microros_distro    = kilted
board_microros_transport = serial

build_flags =
    -L${PROJECT_LIBDEPS_DIR}/esp32dev/micro_ros_arduino/src/esp32
    -lmicroros

lib_archive = false

lib_deps =
    https://github.com/micro-ROS/micro_ros_arduino
    adafruit/Adafruit_VL53L0X@^1.2.4
    DFRobot/DFRobot_BMI160@^1.0.0